FROM node:latest as build-stage

WORKDIR /app

COPY ./package.json ./
COPY ./yarn.lock ./

RUN yarn install

copy ./ .

RUN yarn build

FROM nginx:latest as production-stage
RUN mkdir /app
COPY --from-build-stage /app/build /app
COPY nginx.conf /etc/nginx/nginx.conf
