version: "3"
services:
  react-app:
    image: react-app-dev
    stdin_open: true
    ports: 
      - "3000:3000"
    volumes:
      - ./client/:/usr/src/app
      - /usr/src/app/node_modules
volumes:
  mongo-data:
    driver: local