version: '3'

services:

  # Proxies requests to internal services
  reverse-proxy:
    image: nginx:latest
    container_name: reverse_proxy
    depends_on:
        - frontend
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://localhost"]
      interval: 45s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    volumes:
      - ./reverse_proxy:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    depends_on:
      nginx:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'" 
  frontend:    
    image: personal-client-prod
    container_name: personal-client-prod
    build:
      context: ./client
    ports:
      - "8080:80"
    restart: unless-stopped
