version: "3"
services: 
  server:
    image: personal-site-api
    env_file: ./server/.env
    ports:
      - "5000:5000"
    networks:
      - mern-app
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
  mongo:
    image : mongo
    container_name: mongo
    environment:
      - PUID=1000
      - PGID=1000
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
    logging: 
      driver: none
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
