---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: auth-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: ps-auth-api
  policy:
    semver:
      range: 1.0.x

