apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: auth
  labels:
    name: auth-service
spec:
  selector:
    app: auth
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

