apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-deployment
  namespace: ps-blog-api
  labels:
    app: blog
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 10
      maxUnavailable: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: blog
        image: gcr.io/jonsdevbox/ps_blog_api:1.4.1 # {"$imagepolicy": "flux-system:blog-policy"}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          failureThreshold: 2
          successThreshold: 1
          periodSeconds: 60
        resources:
          limits:
            cpu: "1"
            memory: 100Mi
          requests:
            cpu: 250m
            memory: 20Mi
        volumeMounts:
        - mountPath: /usr/src/.env
          subPath: .env
          name: env
          readOnly: true
      volumes:
      - name: env
        configMap:
          name: personalsite-blog-env
          items:
          - key: .env
            path: .env
