apiVersion: v1
kind: Service
metadata:
  name: contact-service
  namespace: ps-contact-api
  labels:
    name: contact-service
spec:
  selector:
    app: contact
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
