apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-deployment
  namespace: ps-contact-api
  labels:
    app: contact
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 10
      maxUnavailable: 1
  selector:
    matchLabels:
      app: contact
  template:
    metadata:
      labels:
        app: contact
    spec:
      containers:
      - name: contact
        image: gcr.io/jonsdevbox/ps_contact_api:1.1.1 # {"$imagepolicy": "flux-system:contact-policy"}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 60
        resources:
          limits:
            cpu: "1"
            memory: 100Mi
          requests:
            cpu: 250m
            memory: 20Mi
        volumeMounts:
        - mountPath: /usr/src/.env
          subPath: .env
          name: env
          readOnly: true
      volumes:
      - name: env
        configMap:
          name: personalsite-contact-env
          items:
          - key: .env
            path: .env
