---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: contact-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: ps-contact-api
  policy:
    semver:
      range: '>=1.0.0 <2.0.0'

